### PR TITLE
protobuf: Fix label encoding

### PR DESCRIPTION
**Pull request by ackintosh**
Fixes https://github.com/prometheus/client_rust/issues/124

### CODE REVIEW

**Comment by ackintosh** [comment]
I have added a test case to reproduce https://github.com/prometheus/client_rust/issues/124. I was looking into this but couldn't find how to fix. 😓

**Comment by divagant-martian** [comment]
Code is a bit hard to get due to lack of documentation / generic names. Based on the [`text::MetricEncoder`](https://github.com/prometheus/client_rust/blob/9141c118d3c2194c841edca9219dab6d00a19a81/src/encoding/text.rs#L106-L112) field `family_labels`, I assume the [`protobuf::MetricEncoder`](https://github.com/prometheus/client_rust/blob/9141c118d3c2194c841edca9219dab6d00a19a81/src/encoding/protobuf.rs#L109-L113) labels are also meant to be shared labels. 

So if I add this diff
```diff
diff --git a/src/encoding/protobuf.rs b/src/encoding/protobuf.rs
index f40338b..d1f58b2 100644
--- a/src/encoding/protobuf.rs
+++ b/src/encoding/protobuf.rs
@@ -193,6 +193,7 @@ impl<'a> MetricEncoder<'a> {
         &'b mut self,
         label_set: &S,
     ) -> Result<MetricEncoder<'b>, std::fmt::Error> {
+        self.labels.clear();
         label_set.encode(
             LabelSetEncoder {
                 labels: self.labels,
@@ -563,7 +564,7 @@ mod tests {
         family
             .get_or_create(&vec![
                 ("method".to_string(), "GET".to_string()),
-                ("status".to_string(), "200".to_string()),
+                ("status".to_string(), "404".to_string()),
             ])
             .inc();
 
@@ -591,7 +592,7 @@ mod tests {
         assert_eq!("method", metric.labels[0].name);
         assert_eq!("GET", metric.labels[0].value);
         assert_eq!("status", metric.labels[1].name);
-        assert_eq!("200", metric.labels[1].value);
+        assert_eq!("404", metric.labels[1].value);
 
         match extract_metric_point_value(&metric_set) {
             openmetrics_data_model::metric_point::Value::CounterValue(value) => {

```

the test you added gets the correct metric labels, but the test `encoding::protobuf::tests::encode_counter_family_with_prefix_with_label` misses the prefix label.

So I think the problem is that the "family" labels are being populated with normal labels somewhere, can't point to where yet

**Comment by ackintosh** [comment]
I'm not fully sure if I understand current implementation, we should separate labels to e.g. const_labels and family_labels like [text encoding](https://github.com/prometheus/client_rust/blob/9141c118d3c2194c841edca9219dab6d00a19a81/src/encoding/text.rs#L106-L112)? @mxinden How do you think? 🙏

**Comment by mxinden** [comment]
@divagant-martian proposal above, namely to `clear()` the `self.labels` on a call to `encode_family` sounds good to me. This is inline with what the text encoder does, namely to override any existing family labels:

https://github.com/prometheus/client_rust/blob/9141c118d3c2194c841edca9219dab6d00a19a81/src/encoding/text.rs#L210

@ackintosh would you mind applying the suggestion from @divagant-martian?

**Comment by ackintosh** [comment]
I have applied the suggestion but the `encode_counter_family_with_prefix_with_label` test fails. 🤔 

https://github.com/prometheus/client_rust/actions/runs/3958633415/jobs/6780437752#step:9:575
> ---- encoding::protobuf::tests::encode_counter_family_with_prefix_with_label stdout ----
thread 'encoding::protobuf::tests::encode_counter_family_with_prefix_with_label' panicked at 'assertion failed: `(left == right)`
>  left: `3`,
> right: `2`', src/encoding/protobuf.rs:645:9

**Comment by divagant-martian** [comment]
I said this test would fail in my comment

> the test you added gets the correct metric labels, but the test `encoding::protobuf::tests::encode_counter_family_with_prefix_with_label` misses the prefix label.
> 
> So I think the problem is that the "family" labels are being populated with normal labels somewhere, can't point to where yet

So what I think should happen is that this field should be empty in the new test since none of the labels are shared, but populated with the prefix label in the second test. Still don't know where this change should be done tho

**Comment by ackintosh** [comment]
Yeah that is why I said we might want to const_labels and family_labels like text encoding in [my comment](https://github.com/prometheus/client_rust/pull/123#issuecomment-1378044050).

**Comment by ackintosh** [comment]
@mxinden @divagant-martian The bug should have been fixed, please have a look. 🙏

**Comment by ackintosh** [comment]
I have added a doc for `encoding::protobuf::MetricEncoder` for now. 🙂

**Comment by mxinden** [comment]
Thanks for the help here @ackintosh and @divagant-martian!

**Comment by ackintosh** [comment]
@mxinden Could you please cut a new release? I'm thinking of including this fix in rust-libp2p.

**Comment by divagant-martian** [comment]
friendly ping @mxinden for whenever you have the time or if you are waiting on important changes for a release :black_heart:

**Comment by mxinden** [comment]
Sorry for the delay. Tagged and published with https://github.com/prometheus/client_rust/pull/133.

**Pull request merged**
