### PR TITLE
feat(metrics): support `Gauge<u32, AtomicU32>` type

### PR DESCRIPTION
**Pull request by koushiro**
support `Gauge<u32, AtomicU32>` metric

### CODE REVIEW

**Comment by koushiro** [comment]
@mxinden PTAL

**Review by mxinden — COMMENTED** [review]
Cool. Thanks. Looks good to me.

Can you bump the crate version in the root's `Cargo.toml` to `v0.22.2` and add a `CHANGELOG.md` entry? Once this pull request merged, I can then cut a new release right away.

**Comment by mxinden** [comment]
The following test:

``` rust
    #[test]
    fn encode_gauge() {
        let mut registry = Registry::default();
        let gauge = Gauge::<u32, AtomicU32>::default();
        registry.register("my_gauge", "My gauge", gauge);

        let mut encoded = String::new();

        encode(&mut encoded, &registry).unwrap();

        parse_with_python_client(encoded);
    }
```

Would fail with:

```
   --> src/encoding/text.rs:635:51
    |
635 |         registry.register("my_gauge", "My gauge", gauge);
    |                  --------                         ^^^^^ the trait `EncodeGaugeValue` is not implemented for `u32`
    |                  |
    |                  required by a bound introduced by this call
```

Mind adding an implementation of `EncodeGaugeValue` for `u32`? You can cast into an `i64` and then use the existing implementation for `i64`.

Please also extend the `encode_gauge` test in `text.rs` to register both a default `Gauge` and a `Gauge<u32, AtomicU32` to make sure we don't break this in the future.

Sorry for the additional work. Thank you for the help.

**Comment by koushiro** [comment]
Thanks for your feedback, I have changed encoding related stuff and added a simple test case to `encode_gauge`.
@mxinden PTAL again

**Review by mxinden — APPROVED** [review]
Well done!

**Comment by mxinden** [comment]
[Published](https://crates.io/crates/prometheus-client/0.22.2) and [tagged](https://github.com/prometheus/client_rust/releases/tag/v0.22.2).

**Pull request merged**
