### PR TITLE
Add missing tests for some 32-bit types that already work in metrics

### PR DESCRIPTION
**Pull request by navaati**
This adds tests for the new capabilities enabled by #173.

### CODE REVIEW

**Comment by navaati** [comment]
`f32` and `i32` don’t work yet due to missing Atomic implementation.

**Comment by navaati** [comment]
I don’t think changelog edit is required for just adding tests.

**Comment by navaati** [comment]
@mxinden small easy PR, pls review !

**Review by mxinden — APPROVED** [review]
:pray: thanks! More tests is always appreciated.

**Pull request merged**
