### PR TITLE
examples/actix-web.rs: Default enable compress middleware.

### PR DESCRIPTION
**Pull request by jpds**

### CODE REVIEW

**Comment by mxinden** [comment]
Thank you for the proposal.

I still remember compression not being a silver bullet. E.g. see https://github.com/kubernetes/kube-state-metrics/issues/498.

Is this the default in other client libraries? Have you done any measurements with and without?

**Comment by jpds** [comment]
This is the default in the Go library: https://github.com/prometheus/client_golang/blob/93cf5d4f5f78058ef0e5fe5fbf597de2084c64fd/prometheus/promhttp/http.go#L172-L175 - I haven't done any measurements yet.

**Review by mxinden — COMMENTED** [review]
Thank you for the link.

This looks good to me. Can you please fix the `cargo fmt` failure?

**Review by mxinden — APPROVED** [review]
:pray:

**Pull request merged**
